site_name: Kraken
site_description: Phase-field fracture modelling framework


theme: 
    name: 'readthedocs'
    #name: 'material'    
    features:
        - content.code.copy

nav:
  - 📖 About: index.md
  - 📦 Install: install.md


plugins:
  - search
  - mkdocstrings

