name: Deploy documentation

on:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  docs:
    runs-on: ubuntu-latest

    container:
      image: dolfinx/dolfinx:stable

    steps:
      - uses: actions/checkout@v5

      - name: Install Kraken
        run: |
          python3 -m pip install .

      - name: Install documentation packages
        run: |
          python3 -m pip install \
            mkdocs-material \
            "mkdocstrings[python]"

      - name: Build docs
        run: mkdocs build

      - uses: actions/upload-pages-artifact@v3
        with:
          path: site

      - uses: actions/deploy-pages@v4